### ISSUE TITLE
Cannot start DIR-815 example

### ISSUE THREAD

**Issue by BrieflyX** [zyw-200/FirmAFL#14]
I have followed the step to setup the DIR-815 fuzzing environment.
Eventually I executed `python start.py`. However after full system launched, the afl-fuzz failed to handshake with fork server.
It seems that you `chroot` afl-fuzz into a folder and give it a `/bin/busybox` as program? I'm confused with this part. Neither can I `chroot` nor can I find `busybox`. Could you please explain a little bit about this?

**Comment by pureGavin** [comment]
did you solved it? what did you do?
