### ISSUE TITLE
FirmAFL can only Emulate 10 FW?

### ISSUE THREAD

**Issue by Fayozbek** [zyw-200/FirmAFL#28]
Hello Sir
First of all, thank you for realizing this awesome tool.

Would you mind if I give a few questions?

1. Does FirmAFL emulate only 10 firmware that stored in ```FIRMWARE``` folder? How we can emulate other firmware that not included in FIRMWARE folder

3. Is it possible to fuzz that emulated firmware binary out of the FirmAFL folder if I install AFL QEMU mode?

Thank you very much for sharing your time!

**Comment by zyw-200** [comment]
1. If you want to run other firmware, you should modify the configuration file FirmAFL_config.

2. Of course. But there are lots of dependent files that support the emulation. You should move them to the specific directory.

**Comment by Fayozbek** [comment]
Thank you for your response, I will close this issue!
