### ISSUE TITLE
Unable to make FirmAFL work

### ISSUE THREAD

**Issue by josephKhoury95** [zyw-200/FirmAFL#29]
Hello,

I am trying to make FirmAFL running, but I am having a hard time with these below issues:

1. I have **firmadyne** inside the FirmAFL directory, and I am able to execute all the guidance from **firmadyne** correctly, but the image when extracted is named _1.tar.gz_ not _9050.tar.gz_. Subsequently, the created image directory in **FirmAFL** directory is named _image_1_
2. I mentioned the previous point because when running _python FirmAFL_setup.py 9050 mipsel_ it does not work. Also when I tried to execute the command with _1_ like this: _python FirmAFL_setup.py 1 mipsel_ an error pop saying directory _/1/_ does not exist
3. Ok, I tried to do a workaround and rename _1_ to _9050_, and I even created _/1/_ similar to the _/9050/_ directory inside _FirmAFL_config_ directory and went into each file and replaced all _9050_ values with _1_.
4. After doing this workaround it seems it is working even tho I do not find it correct to do it. Now, I go to _/image_1/_ and I execute _sudo python start.py 1_, it will display _sending buffer size 3158_ then an error pop saying _socket.error: [Error 110] Connection timed out_ the execution, however, continues running and at the end, it is stuck on _Spinning up the fork server..._

Can you please help me with the aforementioned concerns, or correct me in case I have a misunderstanding.
Thank you

**Comment by Fayozbek** [comment]
https://github.com/zyw-200/FirmAFL/issues/6#issuecomment-540025952 This will help you!

**Comment by josephKhoury95** [comment]
Thank you @Fayozbek, I read the comment and I will try it.
Meanwhile, I have few questions I hope you can give me their answers:
1. [In this solution that you are referencing](https://github.com/zyw-200/FirmAFL/issues/6#issuecomment-540025952), the author is adding data.xz, do you have any idea why?

Thank you again.

**Comment by Fayozbek** [comment]
Download data.xz from here https://cmu.app.boxcn.net/s/hnpvf1n72uccnhyfe307rc2nb9rfxmjp
This link is given FirmAFL Read.me

**Comment by abdullahqasem** [comment]
> data.xz

this file no longer exist in https://cmu.app.boxcn.net/s/hnpvf1n72uccnhyfe307rc2nb9rfxmjp.
Could anyone upload an alternative link to download data.xz?

**Comment by a4865g** [comment]
> > data.xz
> 
> this file no longer exist in https://cmu.app.boxcn.net/s/hnpvf1n72uccnhyfe307rc2nb9rfxmjp. Could anyone upload an alternative link to download data.xz?

here: https://zenodo.org/record/4922202/files/data.xz?download=1
