### ISSUE TITLE
error when i use "make" command in dir qemu_mode

### ISSUE THREAD

**Issue by pureGavin** [zyw-200/FirmAFL#41]
i try use "make" command in dir qemu_mode but there was an error 

  GEN     config-host.h
make  all-recursive
Making all in pixman
make[3]: Nothing to be done for 'all'.
Making all in demos
make[3]: Nothing to be done for 'all'.
Making all in test
make[3]: Nothing to be done for 'all'.
	CHK version_gen.h
	 LEX convert-dtsv0-lexer.lex.c
make[1]: flex: Command not found
	 LEX dtc-lexer.lex.c
make[1]: flex: Command not found
make: *** No rule to make target 'trace/generated-tcg-tracers.h', needed by 'Makefile'.  Stop.

i search in google but still nothing, what should i do?

**Comment by pureGavin** [comment]
i use ubuntu 18.04 to build it

**Comment by pureGavin** [comment]
i cann't even find 'trace/generated-tcg-tracers.h' file, and which 'Makefile' should i change?

**Comment by pureGavin** [comment]
should i use ubuntu 16.04 ?

**Comment by hcx1chzh** [comment]
Maybe flex and bison should be installed and added to PATH?

**Comment by pureGavin** [comment]
> 也许应该安装flex和bison并将其添加到PATH中？

thanks for help, i already fix it.
i just missing some file when i download it ...

**Comment by pureGavin** [comment]
Use git clone command will be fine. Download zip file and use unzip command if you in China😜
