### ISSUE TITLE
Can I only fuzz the firmware under the ./firmware folder?

### ISSUE THREAD

**Issue by Aaron911** [zyw-200/FirmAFL#8]
When I read the code, I found that I can just fuzz the firmware under the ./firmware folder. Is the configuration written in advance?

**Comment by zyw-200** [comment]
Yes. For now, some configurations such as end point of  fuzzing are embedded in source code. 
You can fuzz other firmwares by changing the logic where "image_id" appears.

**Comment by Aaron911** [comment]
> Yes. For now, some configurations such as end point of fuzzing are embedded in source code.
> You can fuzz other firmwares by changing the logic where "image_id" appears.

OK！I get it。 Thank you very much.
